
[VModConfig]
	#No comment
	SCALE_THRUSTERS_THRUST = true
	#The amount of ticks VMod will try to create constraint if it failed to create one. Why is it needed? VS lags sometimes and fails to create constraints, idk why.
	#Range: > 20
	CONSTRAINT_CREATION_ATTEMPTS = 12000

	[VModConfig.Permissions]
		#No Comment
		#Range: 0 ~ 4
		VMOD_COMMANDS_PERMISSION_LEVEL = 2
		#No Comment
		#Range: 0 ~ 4
		VMOD_OP_COMMANDS_PERMISSION_LEVEL = 4
		#No Comment
		#Range: 0 ~ 4
		VMOD_TOOLGUN_PERMISSION_LEVEL = 2
		#No Comment
		#Range: 0 ~ 4
		VMOD_CHANGING_SERVER_SETTINGS_LEVEL = 4

	[VModConfig.ServerPhysgunSettings]
		#a
		#Range: 0.0 ~ 1.7976931348623157E308
		PCONST = 160.0
		#a
		#Range: 0.0 ~ 1.7976931348623157E308
		DCONST = 20.0
		#a
		#Range: 0.0 ~ 1.7976931348623157E308
		IDKCONST = 90.0

	[VModConfig.Schematics]
		#No Comment
		#Range: > 0
		TIMEOUT_TIME = 50
		#Allows ships to be created over several ticks (so that if you have a huge ship it won't freeze server). May be incompatible with some mods though.
		ALLOW_CHUNK_PLACEMENT_INTERRUPTION = false
		#Allows ships to be updated over several ticks (so that if you have a huge ship it won't freeze server). May be incompatible with some mods though.
		ALLOW_CHUNK_UPDATE_INTERRUPTION = false
		#Determines whenever or not block entities implementing from Container (chests for example) will be loaded
		LOAD_CONTAINERS = true
		#Determines whenever or not entities will be loaded
		LOAD_ENTITIES = true
		#If true, will load nbt of all block entities that are not in blacklist. If false, will only load nbt of whitelisted block entities
		BLACKLIST_MODE = true
		#Write resource location of blocks separated by commas, like "minecraft:chest, some_mod:idk"
		BLACKLIST = ""
		#Write resource location of blocks separated by commas, like "minecraft:chest, some_mod:idk"
		WHITELIST = ""

	[VModConfig.ShipyardPruner]
		#Will automatically delete region files of deleted ships
		CLEAR_SHIP_PLOT_ON_DELETION = true

	[VModConfig.ServerToolgunSettings]
		#No Comment
		#Range: 1.0 ~ 1.7976931348623157E308
		MAX_RAYCAST_DISTANCE = 100.0
		#Reload the game for change to take the effect.
		#Range: 512 ~ 1000000
		SCHEMATIC_PACKET_PART_SIZE = 30000

