name: Build Modpack

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Build Modpack
      run: python build_pack.py

    - name: Archive Client Pack
      run: |
        cd build
        zip -r client-pack.zip client

    - name: Archive Server Pack
      run: |
        cd build
        zip -r server-pack.zip server

    - name: Upload Client Artifact
      uses: actions/upload-artifact@v4
      with:
        name: client-pack
        path: build/client-pack.zip

    - name: Upload Server Artifact
      uses: actions/upload-artifact@v4
      with:
        name: server-pack
        path: build/server-pack.zip
